name: Publish JSON to GitHub Pages

env:
  CNAME_DOMAIN: mailcat.purr.tw
  API_VERSION: 1
  BANK_LIST_JSON: bank_list.json
  BANK_RULE_JSON: bank_rule.json

on:
  push:
    branches: [main]
    paths:
      - "bank_list.json"
      - "bank_rule.json"
      - ".github/workflows/pages.yml"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write
  actions: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy JSON into versioned folder
        run: |
          echo "→ Publishing under: v${API_VERSION}/"
          mkdir -p public/v${API_VERSION}
          cp ${BANK_LIST_JSON} public/v${API_VERSION}/
          cp ${BANK_RULE_JSON} public/v${API_VERSION}/
          echo "${{ env.CNAME_DOMAIN }}" > public/CNAME
          touch public/.nojekyll

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
